In [ ]:
# Data Cleaning and Preprocessing 
In this task, I cleaned the dataset by checking for missing values, removing duplicates, fixing inconsistencies, and changed numerical columns for better understanding and preparing the data for analysis.

In [7]:
import pandas as pd
df= pd. read_csv("3) Sentiment dataset.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [9]:
df.duplicated().sum()

np.int64(0)

In [ ]:
## Handling Duplicates.
I checked for duplicate values, none were found. this indicates that theis dataset is already cleaned in terms of duplication.

In [3]:
df.isnull().sum()

Unnamed: 0.1    0
Unnamed: 0      0
Text            0
Sentiment       0
Timestamp       0
User            0
Platform        0
Hashtags        0
Retweets        0
Likes           0
Country         0
Year            0
Month           0
Day             0
Hour            0
dtype: int64

In [ ]:
## Checking for missing values. 
I checked for missing values in this dataset and i found none.

In [13]:
text_cols = ['Sentiment', 'Platform', 'Country','Text']
df[text_cols] = df[text_cols].apply(lambda x: x.str.strip().str.lower())
df.head()

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,enjoying a beautiful day at the park!,positive,2023-01-15 12:30:00,User123,twitter,#Nature #Park,15.0,30.0,usa,2023,1,15,12
1,traffic was terrible this morning.,negative,2023-01-15 08:45:00,CommuterX,twitter,#Traffic #Morning,5.0,10.0,canada,2023,1,15,8
2,just finished an amazing workout! 💪,positive,2023-01-15 15:45:00,FitnessFan,instagram,#Fitness #Workout,20.0,40.0,usa,2023,1,15,15
3,excited about the upcoming weekend getaway!,positive,2023-01-15 18:20:00,AdventureX,facebook,#Travel #Adventure,8.0,15.0,uk,2023,1,15,18
4,trying out a new recipe for dinner tonight.,neutral,2023-01-15 19:55:00,ChefCook,instagram,#Cooking #Food,12.0,25.0,australia,2023,1,15,19

In [ ]:
## Fixing Inconsistencies. 
I observed some inconsistencies in some of the categorical columns, such as the Sentiment, Platform, Country, and Text, where values have different letter cases. 
To ensure uniformity and consistency, i converted all entries in these column to lower case letters.

In [17]:
df['Likes'] = df['Likes'].astype(int)
df['Retweets'] = df['Retweets'].astype(int)
df.head()

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,enjoying a beautiful day at the park!,positive,2023-01-15 12:30:00,User123,twitter,#Nature #Park,15,30,usa,2023,1,15,12
1,traffic was terrible this morning.,negative,2023-01-15 08:45:00,CommuterX,twitter,#Traffic #Morning,5,10,canada,2023,1,15,8
2,just finished an amazing workout! 💪,positive,2023-01-15 15:45:00,FitnessFan,instagram,#Fitness #Workout,20,40,usa,2023,1,15,15
3,excited about the upcoming weekend getaway!,positive,2023-01-15 18:20:00,AdventureX,facebook,#Travel #Adventure,8,15,uk,2023,1,15,18
4,trying out a new recipe for dinner tonight.,neutral,2023-01-15 19:55:00,ChefCook,instagram,#Cooking #Food,12,25,australia,2023,1,15,19

In [ ]:
## Data Type Conversion. 
I noticed some numerical columns, such as likes and retweets, which were stored in float formart, so i converted them to integers, to make the data understandable and suitable for analysis.

In [ ]:
## Conclusion. 
This dataset is now ready and clean for analysis.

In [18]:
df.to_csv("cleaned_data.csv", index=False)